import { useState, useEffect } from 'react';

function Reports() {
  const [profit, setProfit] = useState(null);
  const [topBooks, setTopBooks] = useState([]);
  const [salesTrend, setSalesTrend] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      setLoading(true);
      const [profitRes, topBooksRes, trendRes] = await Promise.all([
        fetch('http://localhost:5050/api/reports/profit'),
        fetch('http://localhost:5050/api/reports/top-books?limit=5'),
        fetch('http://localhost:5050/api/reports/sales-trend')
      ]);
      const profitData = await profitRes.json();
      const topBooksData = await topBooksRes.json();
      const trendData = await trendRes.json();
      setProfit(profitData);
      setTopBooks(Array.isArray(topBooksData) ? topBooksData : []);
      setSalesTrend(Array.isArray(trendData) ? trendData : []);
    } catch (error) {
      console.error('Failed to load reports:', error);
      setProfit({ revenue: 0, cost: 0, profit: 0 });
      setTopBooks([]);
      setSalesTrend([]);
    } finally {
      setLoading(false);
    }
  };

  // ── EXPORT TO PDF (Profit Summary only) ──
  const exportToPDF = () => {
    const today = new Date().toLocaleDateString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
    });

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8"/>
        <title>Profit Summary Report</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; background: #fff; padding: 40px; }
          .header { text-align: center; border-bottom: 3px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { font-size: 28px; color: #3b82f6; font-weight: 800; }
          .header p { font-size: 13px; color: #666; margin-top: 6px; }
          .section h2 { font-size: 16px; font-weight: 700; color: #1e293b; margin-bottom: 20px; padding-left: 10px; border-left: 4px solid #3b82f6; }
          .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }
          .summary-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; text-align: center; }
          .summary-box.highlight { background: #eff6ff; border-color: #3b82f6; }
          .summary-box .label { font-size: 12px; color: #64748b; margin-bottom: 8px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.05em; }
          .summary-box .value { font-size: 26px; font-weight: 800; color: #1e293b; }
          .summary-box.highlight .value { color: #3b82f6; }
          .footer { text-align: center; margin-top: 50px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>📚 TN Book Store</h1>
          <p>Profit Summary Report — ${today}</p>
        </div>

        <div class="section">
          <h2>Financial Summary</h2>
          <div class="summary-grid">
            <div class="summary-box">
              <div class="label">Today's Revenue</div>
              <div class="value">Rs. ${Number(profit?.revenue || 0).toFixed(2)}</div>
            </div>
            <div class="summary-box">
              <div class="label">Cost of Goods</div>
              <div class="value">Rs. ${Number(profit?.cost || 0).toFixed(2)}</div>
            </div>
            <div class="summary-box highlight">
              <div class="label">Net Profit</div>
              <div class="value">Rs. ${Number(profit?.profit || 0).toFixed(2)}</div>
            </div>
          </div>
        </div>

        <div class="footer">
          Generated by Bookshop ERP v2.0 Pro &nbsp;|&nbsp; ${new Date().toLocaleString()}
        </div>
      </body>
      </html>
    `;

    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); }, 500);
  };

  // ── EXPORT TO EXCEL (Everything) ──
  const exportToExcel = () => {
    const today = new Date().toLocaleDateString('en-US');
    let csv = '';

    csv += 'FINANCIAL SUMMARY\n';
    csv += `Date,${today}\n`;
    csv += `Today's Revenue,Rs. ${Number(profit?.revenue || 0).toFixed(2)}\n`;
    csv += `Cost of Goods,Rs. ${Number(profit?.cost || 0).toFixed(2)}\n`;
    csv += `Net Profit,Rs. ${Number(profit?.profit || 0).toFixed(2)}\n`;
    csv += '\n';

    csv += 'TOP SELLING BOOKS\n';
    csv += 'Rank,Title,Author,Qty Sold,Revenue\n';
    if (topBooks.length === 0) {
      csv += 'No sales data available\n';
    } else {
      topBooks.forEach((book, i) => {
        csv += `#${i + 1},"${book.title}","${book.author}",${book.total_sold},Rs. ${Number(book.revenue || 0).toFixed(2)}\n`;
      });
    }
    csv += '\n';

    csv += 'SALES TREND (LAST 7 DAYS)\n';
    csv += 'Date,Bills,Revenue\n';
    if (salesTrend.length === 0) {
      csv += 'No sales data available\n';
    } else {
      salesTrend.forEach(day => {
        csv += `${new Date(day.date).toLocaleDateString('en-US')},${day.bills},Rs. ${Number(day.revenue || 0).toFixed(2)}\n`;
      });
    }

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bookshop-report-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="reports-loading">
        <div className="spinner"></div>
        <p>Loading reports...</p>
      </div>
    );
  }

  const maxRevenue = salesTrend.length > 0
    ? Math.max(...salesTrend.map(d => Number(d.revenue) || 0))
    : 1;

  return (
    <div className="reports-page">
      <div className="reports-header">
        <h2>📈 Analytics & Reports</h2>
        <button className="refresh-btn" onClick={loadReports}>
          🔄 Refresh
        </button>
      </div>

      {/* Profit Summary */}
      <div className="profit-summary">
        <div className="profit-card">
          <div className="profit-icon">💰</div>
          <div className="profit-content">
            <div className="profit-label">Today's Revenue</div>
            <div className="profit-value">Rs. {Number(profit?.revenue || 0).toFixed(2)}</div>
          </div>
        </div>
        <div className="profit-card">
          <div className="profit-icon">📊</div>
          <div className="profit-content">
            <div className="profit-label">Cost of Goods</div>
            <div className="profit-value">Rs. {Number(profit?.cost || 0).toFixed(2)}</div>
          </div>
        </div>
        <div className="profit-card highlight">
          <div className="profit-icon">✨</div>
          <div className="profit-content">
            <div className="profit-label">Net Profit</div>
            <div className="profit-value">Rs. {Number(profit?.profit || 0).toFixed(2)}</div>
          </div>
        </div>
      </div>

      <div className="reports-grid">

        {/* Top Selling Books */}
        <div className="report-card">
          <h3>📚 Top Selling Books</h3>
          {topBooks.length === 0 ? (
            <div className="no-data">No sales data available</div>
          ) : (
            <div className="top-books-list">
              {topBooks.map((book, index) => (
                <div key={index} className="top-book-item">
                  <div className="rank">#{index + 1}</div>
                  <div className="book-info">
                    <div className="book-name">{book.title}</div>
                    <div className="book-author">{book.author}</div>
                  </div>
                  <div className="book-stats">
                    <div className="stat">
                      <span className="stat-label">Sold:</span>
                      <span className="stat-value">{book.total_sold}</span>
                    </div>
                    <div className="stat">
                      <span className="stat-label">Revenue:</span>
                      <span className="stat-value">Rs. {Number(book.revenue || 0).toFixed(2)}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Sales Trend */}
        <div className="report-card">
          <h3>📊 Sales Trend (Last 7 Days)</h3>
          {salesTrend.length === 0 ? (
            <div className="no-data">No sales data available</div>
          ) : (
            <div className="trend-list">
              {salesTrend.map((day, index) => (
                <div key={index} className="trend-item">
                  <div className="trend-date">
                    {new Date(day.date).toLocaleDateString('en-US', {
                      month: 'short', day: 'numeric'
                    })}
                  </div>
                  <div className="trend-bar-container">
                    <div
                      className="trend-bar"
                      style={{
                        width: `${maxRevenue > 0 ? (Number(day.revenue) / maxRevenue) * 100 : 0}%`
                      }}
                    ></div>
                  </div>
                  <div className="trend-stats">
                    <span className="trend-bills">{day.bills} bills</span>
                    <span className="trend-revenue">Rs. {Number(day.revenue || 0).toFixed(2)}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>

      {/* Export Options */}
      <div className="export-section">
        <h3>📄 Export Reports</h3>
        <div className="export-buttons">
          <button className="export-btn" onClick={exportToExcel}>
            <span>📊</span> Export to Excel
          </button>
          <button className="export-btn" onClick={exportToPDF}>
            <span>📄</span> Export to PDF
          </button>
        </div>
      </div>
    </div>
  );
}


export default Reports;